Import zamarrenolm's improvements

diff --git a/.github/workflows/nightly-release.yml b/.github/workflows/nightly-release.yml
--- a/.github/workflows/nightly-release.yml
+++ b/.github/workflows/nightly-release.yml
@@ -23,7 +23,6 @@ jobs:
       VERSION: "1.3.0"
       GH_API: https://api.github.com/repos/sheosi/dynawo-algorithms
       CURL_JSON: 'curl -s -H "Content-Type": "application/json"'
-      CURL_ZIP: 'curl -H "Content-Type": "application/zip" --retry 20 --retry-delay 0 --retry-max-time 40'
 
 
     steps:
@@ -55,17 +54,14 @@ jobs:
             fi
           }
           
-          download_asset sheosi/dynawo Dynawo_headers_Nightly.zip
+          download_asset dynawo/dynawo Dynawo_headers_V${VERSION}.zip
           
       - name: Extract Dynawo
         run: |
           unzip -qq "Dynawo_headers_Nightly.zip"
           cd ..
           
-          # Write
-          pwd
-          ls
-          echo DEBUG write dynawoEnv
+          # Write dynawoEnv file, which isn't contained inside the distribution
           cat > dynawo-algorithms/dynawo/dynawoEnv.txt  << EOF 
           DYNAWO_ADEPT_INSTALL_DIR="/__w/dynawo/dynawo/install/3rdParty/gcc5.3.1/shared/Release-cxx11/adept"
           DYNAWO_BOOST_HOME="/__w/dynawo/dynawo/install/3rdParty/gcc5.3.1/shared/Release-cxx11/boost"
@@ -137,10 +133,6 @@ jobs:
           DYNAWO_ZLIB_HOME="/__w/dynawo/dynawo/install/3rdParty/gcc5.3.1/shared/Release-cxx11/zlib"
           DYNAWO_ZLIB_HOME_DEFAULT="false"
           EOF
-          
-          echo "Debug. env file"
-          cat dynawo-algorithms/dynawo/dynawoEnv.txt
-
 
       - name: Build
         run: |
@@ -154,32 +146,112 @@ jobs:
           export DYNAWO_ALGORITHMS_HOME=$(pwd)
           util/envDynawoAlgorithms.sh distrib
           util/envDynawoAlgorithms.sh distrib-headers
+      - name: INFO. Files created in distributions folder
+        run: du -hs distributions/*
 
-      - name: Delete old tag and release
+      - name: Delete previous nightly release
         run: |
-          $CURL_JSON -u "user:${{ secrets.GITHUB_TOKEN }}" -w '%{http_code}\n'  -X DELETE  "$GH_API/git/refs/tags/nightly"
-          RELEASE_ID=$( $CURL_JSON -X GET "$GH_API/releases" |  python3 -c 'import sys, json;l=[x for x in json.load(sys.stdin) if x["tag_name"]=="nightly"];print(str(l[0]["id"]) if l else "")')
-          
+          source .github/workflows/tools.sh
+          echo "Obtain previous release id and delete it"
+          RELEASE_ID=$($CURL_JSON "$GH_API/releases" | python3 -c 'import sys, json; releases=[release["id"] for release in json.load(sys.stdin) if release["tag_name"]=="nightly"]; print(releases[0] if releases else "")')
           if [ ! -z "$RELEASE_ID" ]; then
-            $CURL_JSON -u "user:${{ secrets.GITHUB_TOKEN }}" -w '%{http_code}\n' -X DELETE "$GH_API/releases/$RELEASE_ID"
+            echo "Release id with tag 'nightly' found: $RELEASE_ID"
+            echo "Delete release $RELEASE_ID ..."
+            curl \
+              --request DELETE \
+              --url "$GH_API/releases/$RELEASE_ID" \
+              --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
+            echo "Wait for release to be deleted ..."
+            wait_for_http_code "$GH_API/releases/$RELEASE_ID" 404
           else
-            echo "Nightly release not found, won't be deleted"
+            echo "Previous nightly release not found"
           fi
+      - name: INFO. List of all releases after deleting nightly
+        run: $CURL_JSON "$GH_API/releases"
+
+
+      - name: Delete previous nightly tag
+        run: |
+          source .github/workflows/tools.sh
+          echo "Delete previous tag. Won't fail if it does not exist"
+          curl \
+            --request DELETE \
+            --url "$GH_API/git/refs/tags/nightly" \
+            --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            --header "Content-Type: application/json"
+          echo "Wait for tag to be deleted ..."
+          wait_for_http_code "$GH_API/git/refs/tags/nightly" 404
+      - name: INFO. Nightly tag should not be found
+        run: $CURL_JSON "$GH_API/git/refs/tags/nightly"
 
       - name: Get last commit in master
         id: commit_id
         run: |
-          echo "::set-output name=MASTER_COMMIT_ID::$($CURL_JSON -X GET  $GH_API/git/refs/heads/master| python3 -c 'import sys, json; print(json.load(sys.stdin)["object"]["sha"])')"
+          echo "Obtaining refs/heads/master ..."
+          HEAD_MASTER=$($CURL_JSON "$GH_API/git/refs/heads/master")
+          echo "Head master:"
+          echo $HEAD_MASTER
+          SHA_HEAD_MASTER=$(echo $HEAD_MASTER | python3 -c 'import sys, json; print(json.load(sys.stdin)["object"]["sha"])')
+          echo "Last commit in master has SHA = $SHA_HEAD_MASTER"
+          echo "MASTER_COMMIT_ID=$SHA_HEAD_MASTER" >> $GITHUB_ENV
+      - name: INFO. Check last commit in master
+        run: echo "Last commit in master SHA = $MASTER_COMMIT_ID"
 
-      - name: Create Nightly Tag
+      - name: Create tag Nightly
         run: |
-          $CURL_JSON -u "user:${{ secrets.GITHUB_TOKEN }}" -w '%{http_code}\n' -X POST  -d '{"ref":"refs/tags/nightly", "sha":"${{ steps.commit_id.outputs.MASTER_COMMIT_ID }}" }'  "$GH_API/git/refs"
+          source .github/workflows/tools.sh
+          echo "Create tag nightly based on last commit in master branch"
+          curl \
+            --request POST \
+            --url "$GH_API/git/refs" \
+            --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            --header "Content-Type: application/json" \
+            --data '{
+                "ref": "refs/tags/nightly",
+                "sha": "'$MASTER_COMMIT_ID'"
+                }'
+          echo "Wait for tag to be created ..."
+          wait_for_http_code "$GH_API/git/refs/tags/nightly" 200
+      - name: INFO. Tag nightly created"
+        run: $CURL_JSON "$GH_API/git/refs/tags/nightly"
 
-
-      - name: Release
+      - name: Create release nightly
         run: |
-          $CURL_JSON -X POST -u "user:${{ secrets.GITHUB_TOKEN }}" $GH_API/releases -d $'{"tag_name":"nightly", "target_commitish": "${{ steps.commit_id.outputs.MASTER_COMMIT_ID }}", "name": "Nightly", "body": "Dynawo\'s nightly release. Compiled on *release* settings.\\n\\n **Don\'t use it for production**", "draft": false, "prerelease": true }'
-          sleep 60 # Wait for release to be published
-          UPLOAD_URL=$(curl -s -X GET $GH_API/releases | python3 -c 'import sys, json;l=[x for x in json.load(sys.stdin) if x["tag_name"]=="nightly"];print(str(l[0]["upload_url"]))' | grep -o ".*assets")
-          $CURL_ZIP -u "user:${{ secrets.GITHUB_TOKEN }}" -X POST $UPLOAD_URL?name=Dynawo_algorithms_Nightly.zip  -H "Content-Type: application/zip" --retry 20 --retry-delay 0 --retry-max-time 40 --data-binary @distributions/Dynawo_algorithms_V$VERSION.zip
-          $CURL_ZIP -u "user:${{ secrets.GITHUB_TOKEN }}" -X POST $UPLOAD_URL?name=Dynawo_algorithms_headers_Nightly.zip  -H "Content-Type: application/zip" --retry 20 --retry-delay 0 --retry-max-time 40 --data-binary @distributions/Dynawo_algorithms_headers_V$VERSION.zip
+          source .github/workflows/tools.sh
+          echo "Create release nightly"
+          curl \
+            --request POST \
+            --url "$GH_API/releases" \
+            --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            --header "Content-Type: application/json" \
+            --data '{
+                "tag_name" : "nightly",
+                "target_commitish" : "'$MASTER_COMMIT_ID'",
+                "name" : "Nightly",
+                "body" : "Dynawo'"'"'s nightly release. Compiled on *release* settings.\n\n**Don'"'"'t use it for production**",
+                "draft" : false,
+                "prerelease" : true
+                }'
+          echo "Wait for the release to be published ..."
+          wait_for_http_code "$GH_API/releases/tags/nightly" 200
+      - name: INFO. Release object created for tag nightly"
+        run: $CURL_JSON "$GH_API/releases/tags/nightly"
+
+      - name: Upload assets for release
+        run: |
+          source .github/workflows/tools.sh
+          echo "Obtain upload and assets urls from created release:"
+          RELEASE=$($CURL_JSON "$GH_API/releases/tags/nightly")
+          UPLOAD_URL=$(echo ${RELEASE} | python3 -c 'import sys, json; release = json.load(sys.stdin); print(str(release["upload_url"]))' | grep -o ".*assets")
+          echo "Release upload URL = $UPLOAD_URL"
+          ASSETS_URL=$(echo ${RELEASE} | python3 -c 'import sys, json; release = json.load(sys.stdin); print(str(release["assets_url"]))')
+          echo "Release assets URL = $ASSETS_URL"
+          echo "ASSETS_URL=$ASSETS_URL" >> $GITHUB_ENV
+          echo "Upload assets"
+          for FILE in distributions/*zip; do
+            [ -f "$FILE" ] || break
+            echo "Upload asset $FILE"
+            upload_zip_file $UPLOAD_URL $FILE ${{ secrets.GITHUB_TOKEN }}
+          done
+      - name: INFO. Release assets
+        run: $CURL_JSON $ASSETS_URL
